version: '2.4'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    volumes:
      # - "./localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
