service: backup-slack

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  environment: ${self:custom.environment.${sls:stage}}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: 
            - "lambda:InvokeFunction"
            - "lambda:GetFunction"
          Resource: "*"

plugins:
  - serverless-python-requirements
  - serverless-localstack

custom:
  localstack:
    stages: [local]
    host: http://localstack
  environment:
    local:
      NOTION_API_KEY: ${ssm:/rotom_bot/${sls:stage}/notion/NOTION_API_KEY}
      BACKUP_MESSAGES_DATABASE_ID: ${ssm:/rotom_bot/${sls:stage}/notion/BACKUP_MESSAGES_DATABASE_ID}
      BACKUP_CHANNELS_DATABASE_ID: ${ssm:/rotom_bot/${sls:stage}/notion/BACKUP_CHANNELS_DATABASE_ID}
      BACKUP_USERS_DATABASE_ID: ${ssm:/rotom_bot/${sls:stage}/notion/BACKUP_USERS_DATABASE_ID}
      SLACK_BOT_TOKEN: ${ssm:/rotom_bot/${sls:stage}/slack/SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${ssm:/rotom_bot/${sls:stage}/slack/SLACK_SIGNING_SECRET}
      LOCALSTACK_HOSTNAME: localstack
      EDGE_PORT: 4566

functions:
  backup_messages:
    handler: handler/backup_messages.handler
    events:
      - http:
          path: slack/events
          method: post
