service: backup-slack

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  profile: ${self:custom.profiles.${sls:stage}}


plugins:
  - serverless-localstack

custom:
  localstack:
    stages: [local]
    host: http://localstack
  profiles:
    local: local
    prod: prod

functions:
  backup_messages:
    handler: handler/backup_messages.lambda_handler
