name: Test

on: 
  pull_request: {}
  push:
    branches: main
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: nektos/act specific settings
        if: ${{ env.ACT }}
        run: |
          sudo apt-get update &&
          apt-get install -y docker-compose
          docker --version
          docker-compose -v

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.14

      - name: run all tests
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run devtools run-test

      # - run: pipenv run isort --recursive --diff .
      # - run: pipenv run black --check .
      # - run: pipenv run flake8
      # - run: pipenv run mypy
      # - run: pipenv run pytest --cov # --cov-fail-under=100
